<?php
add_action('acf/include_fields', function () {
    if (! function_exists('acf_add_local_field_group')) {
        return;
    }
    acf_add_local_field_group(array(
        'key' => 'group_6833383464a51',
        'title' => 'AiM Tool Settings',
        'fields' => array(
            array(
                'key' => 'field_68333834f0dc3',
                'label' => 'Tool Url',
                'name' => 'aim_tool_url',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_aim-tool-icon',
                'label' => 'Tool Icon',
                'name' => 'aim_tool_icon',
                'aria-label' => '',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'aim-tool',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));
    acf_add_local_field_group(array(
        'key' => 'group_67d06752edff8',
        'title' => 'Lesson Category Options',
        'fields' => array(
            array(
                'key' => 'field_67d0675390772',
                'label' => 'Color',
                'name' => 'color',
                'aria-label' => '',
                'type' => 'color_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '#49DBA6',
                'enable_opacity' => 0,
                'return_format' => 'string',
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_67e86cfb53446',
                'label' => 'Singular Label',
                'name' => 'single',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => 'Category Label Should be plural and this fields should be the single version',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'allow_in_bindings' => 0,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'ld_lesson_category',
                ),
            ),
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'ai-skill-level',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

    acf_add_local_field_group(array(
        'key' => 'group_67d065ff7e536',
        'title' => 'Session Options',
        'fields' => array(
            array(
                'key' => 'field_67d065ff9f328',
                'label' => 'Session Month',
                'name' => 'session_date',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'F',
                'return_format' => 'F',
                'first_day' => 1,
                'allow_in_bindings' => 0,
            ),
            array(
                'key' => 'field_67e80fccff1f6',
                'label' => 'Coming Soon?',
                'name' => 'coming_soon',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => 'If the session has not happened yet check it',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => 'Display Coming Soon Card',
                'default_value' => 0,
                'allow_in_bindings' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sfwd-lessons',
                ),
                array(
                    'param' => 'post_taxonomy',
                    'operator' => '==',
                    'value' => 'ld_lesson_category:session-lecture',
                ),
            ),
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'sfwd-lessons',
                ),
                array(
                    'param' => 'post_taxonomy',
                    'operator' => '==',
                    'value' => 'ld_lesson_category:session-lab',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 1,
    ));
});

add_action('init', function () {
    register_taxonomy('aim-tool-category', array(
        0 => 'aim-tool',
    ), array(
        'labels' => array(
            'name' => 'AiM Tool Categories',
            'singular_name' => 'AiM Tool Category',
            'menu_name' => 'AiM Tool Categories',
            'all_items' => 'All AiM Tool Categories',
            'edit_item' => 'Edit AiM Tool Category',
            'view_item' => 'View AiM Tool Category',
            'update_item' => 'Update AiM Tool Category',
            'add_new_item' => 'Add New AiM Tool Category',
            'new_item_name' => 'New AiM Tool Category Name',
            'search_items' => 'Search AiM Tool Categories',
            'popular_items' => 'Popular AiM Tool Categories',
            'separate_items_with_commas' => 'Separate aim tool categories with commas',
            'add_or_remove_items' => 'Add or remove aim tool categories',
            'choose_from_most_used' => 'Choose from the most used aim tool categories',
            'not_found' => 'No aim tool categories found',
            'no_terms' => 'No aim tool categories',
            'items_list_navigation' => 'AiM Tool Categories list navigation',
            'items_list' => 'AiM Tool Categories list',
            'back_to_items' => '← Go to aim tool categories',
            'item_link' => 'AiM Tool Category Link',
            'item_link_description' => 'A link to a aim tool category',
        ),
        'public' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
    ));
});

add_action('init', function () {
    register_post_type('aim-tool', array(
        'labels' => array(
            'name' => 'AiM Tools',
            'singular_name' => 'AiM Tool',
            'menu_name' => 'AiM Tools',
            'all_items' => 'All AiM Tools',
            'edit_item' => 'Edit AiM Tool',
            'view_item' => 'View AiM Tool',
            'view_items' => 'View AiM Tools',
            'add_new_item' => 'Add New AiM Tool',
            'add_new' => 'Add New AiM Tool',
            'new_item' => 'New AiM Tool',
            'parent_item_colon' => 'Parent AiM Tool:',
            'search_items' => 'Search AiM Tools',
            'not_found' => 'No aim tools found',
            'not_found_in_trash' => 'No aim tools found in Trash',
            'archives' => 'AiM Tool Archives',
            'attributes' => 'AiM Tool Attributes',
            'insert_into_item' => 'Insert into aim tool',
            'uploaded_to_this_item' => 'Uploaded to this aim tool',
            'filter_items_list' => 'Filter aim tools list',
            'filter_by_date' => 'Filter aim tools by date',
            'items_list_navigation' => 'AiM Tools list navigation',
            'items_list' => 'AiM Tools list',
            'item_published' => 'AiM Tool published.',
            'item_published_privately' => 'AiM Tool published privately.',
            'item_reverted_to_draft' => 'AiM Tool reverted to draft.',
            'item_scheduled' => 'AiM Tool scheduled.',
            'item_updated' => 'AiM Tool updated.',
            'item_link' => 'AiM Tool Link',
            'item_link_description' => 'A link to a aim tool.',
        ),
        'public' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-admin-post',
        'supports' => array(
            0 => 'title',
            1 => 'editor',
            2 => 'thumbnail',
            3 => 'custom-fields',
        ),
        'delete_with_user' => false,
    ));
});

add_action('init', function () {
    register_taxonomy('ai-skill-level', array(
        0 => 'sfwd-lessons',
    ), array(
        'labels' => array(
            'name' => 'Ai Skill Levels',
            'singular_name' => 'Ai Skill Level',
            'menu_name' => 'Ai Skill Levels',
            'all_items' => 'All Ai Skill Levels',
            'edit_item' => 'Edit Ai Skill Level',
            'view_item' => 'View Ai Skill Level',
            'update_item' => 'Update Ai Skill Level',
            'add_new_item' => 'Add New Ai Skill Level',
            'new_item_name' => 'New Ai Skill Level Name',
            'search_items' => 'Search Ai Skill Levels',
            'not_found' => 'No ai skill levels found',
            'no_terms' => 'No ai skill levels',
            'items_list_navigation' => 'Ai Skill Levels list navigation',
            'items_list' => 'Ai Skill Levels list',
            'back_to_items' => '← Go to ai skill levels',
            'item_link' => 'Ai Skill Level Link',
            'item_link_description' => 'A link to a ai skill level',
        ),
        'public' => true,
        'hierarchical' => true,
        'show_in_menu' => true,
        'show_in_rest' => true,
        'rewrite' => array(
            'hierarchical' => true,
        ),
    ));
});
